# Generated by Django 4.1 on 2022-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_wine_id_auctionlisting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_maximum_bid',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
