# Generated by Django 4.1 on 2022-09-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionlisting_current_maximum_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_maximum_bid',
        ),
    ]
