# Generated by Django 4.1 on 2022-09-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_auctionlisting_current_maximum_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='max_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
