# Generated by Django 4.1 on 2022-09-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlisting_max_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='last_bid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
