# Generated by Django 4.1 on 2022-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlisting_last_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='last_bidder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
