# Generated by Django 4.1 on 2022-09-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_last_bid_date_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
