# Generated by Django 4.1 on 2022-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_bid_bid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
