# Generated by Django 4.1 on 2022-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0002_manufacturer_remove_wine_color_remove_wine_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='grape_variety',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sold_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
