# Generated by Django 4.1 on 2022-08-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0006_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
