# Generated by Django 4.1 on 2022-08-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0008_remove_profile_name_alter_profile_auction_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auction_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='feedback_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sold_items',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
    ]
