# Generated by Django 4.1 on 2022-08-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0009_remove_profile_auction_limit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
