# Generated by Django 4.1 on 2022-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0011_remove_cart_date_added_remove_cart_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
