# Generated by Django 4.1 on 2022-08-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0013_wine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
