# Generated by Django 4.1 on 2022-08-30 17:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0014_manufacturer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('cart', 'In cart'), ('checkout', 'In checkout'), ('done', 'Transaction completed')], default='cart', max_length=100),
        ),
    ]
