# Generated by Django 4.1 on 2022-08-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0016_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
