# Generated by Django 4.1 on 2022-09-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0018_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='id',
            new_name='id',
        ),
    ]
