# Generated by Django 4.1.1 on 2022-09-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0019_rename_wine_id_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='variety',
        ),
    ]
