# Generated by Django 4.1.1 on 2022-09-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warket_viewer', '0020_remove_wine_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
