# Generated by Django 4.1 on 2022-09-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winesearch',
            old_name='id',
            new_name='id',
        ),
    ]
